### ISSUE TITLE
Misleading CLI help

### ISSUE THREAD

**Issue by claui** [claui/cookiecutter-python-package#41]
After scaffolding the project, command names are duplicated in the help text output:

```shell
$ FOOBAR=baz poetry run poe hello --help
INFO: Showing help with the command 'hello hello -- --help'.

NAME
    hello hello - Says hello to someone.

SYNOPSIS
    hello hello <flags>

DESCRIPTION
    Says hello to someone.

FLAGS
    -n, --name=NAME
        Type: str
        Default: 'world'
```

The first `hello` is the `hello` from `tool.poe.tasks.hello`.

The second `hello` appears to come from the value of `tool.poe.tasks.hello.script`:

```toml
[tool.poetry.scripts]
flub = "flubber.cli:run"

[tool.poe.tasks]
hello.script = "myproject.cli:run('hello')"
```

- The script name in `tool.poetry.scripts` should have the same name as the poethepoet script.

- If a script has no subcommands, it should run `cli` (or a copy of `cli`) without arguments.
